version: "3.8"

services:
  mysql:
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - ${DB_PORT:-3306}:${DB_PORT:-3306}
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASS:-testpassword}
      - MYSQL_PASSWORD=${DB_PASS:-testpassword}
      - MYSQL_DATABASE=${DB_NAME:-task_master}
      - MYSQL_TCP_PORT=${DB_PORT:-3306}

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  localstack:
    image: localstack/localstack
    network_mode: bridge
    ports:
      - "4566:4566"            # LocalStack Gateway
      - "4510-4559:4510-4559"  # external services port range
    environment:
      - DEBUG=${DEBUG-}
      - DOCKER_HOST=${DOCKER_HOST:-unix:///var/run/docker.sock}
      - PERSISTENCE=1
      - LAMBDA_KEEPALIVE_MS=300000
      - LAMBDA_EXECUTOR=docker
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./.esbuild:/esbuild"

networks:
  default:
    name: task_master
